// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: batch.go

package sqlc

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const insertBallots = `-- name: InsertBallots :batchexec
INSERT INTO ballots(id, section_id, judge_id, side, entry_id, started, result)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT(id) DO UPDATE
    SET section_id = EXCLUDED.section_id,
        judge_id   = EXCLUDED.judge_id,
        side       = EXCLUDED.side,
        entry_id   = EXCLUDED.entry_id,
        started    = EXCLUDED.started,
        result     = EXCLUDED.result
`

type InsertBallotsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertBallotsParams struct {
	ID        int32
	SectionID pgtype.Int4
	JudgeID   pgtype.Int4
	Side      NullBallotSide
	EntryID   pgtype.Int4
	Started   pgtype.Bool
	Result    NullBallotResult
}

func (q *Queries) InsertBallots(ctx context.Context, arg []InsertBallotsParams) *InsertBallotsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.SectionID,
			a.JudgeID,
			a.Side,
			a.EntryID,
			a.Started,
			a.Result,
		}
		batch.Queue(insertBallots, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertBallotsBatchResults{br, len(arg), false}
}

func (b *InsertBallotsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertBallotsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertEntry = `-- name: InsertEntry :batchexec
INSERT INTO entries(id, tournament_id, event_id, code, active)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT(id) DO UPDATE
    SET tournament_id = EXCLUDED.tournament_id,
        event_id      = EXCLUDED.event_id,
        code          = EXCLUDED.code,
        active        = EXCLUDED.active
`

type InsertEntryBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertEntryParams struct {
	ID           pgtype.Int4
	TournamentID pgtype.Int4
	EventID      pgtype.Int4
	Code         pgtype.Text
	Active       pgtype.Bool
}

func (q *Queries) InsertEntry(ctx context.Context, arg []InsertEntryParams) *InsertEntryBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.TournamentID,
			a.EventID,
			a.Code,
			a.Active,
		}
		batch.Queue(insertEntry, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertEntryBatchResults{br, len(arg), false}
}

func (b *InsertEntryBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertEntryBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertEvent = `-- name: InsertEvent :batchexec
INSERT INTO events(id, tournament_id, name)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE
    SET tournament_id = EXCLUDED.tournament_id,
        name          = EXCLUDED.name
`

type InsertEventBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertEventParams struct {
	ID           int32
	TournamentID pgtype.Int4
	Name         pgtype.Text
}

func (q *Queries) InsertEvent(ctx context.Context, arg []InsertEventParams) *InsertEventBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.TournamentID,
			a.Name,
		}
		batch.Queue(insertEvent, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertEventBatchResults{br, len(arg), false}
}

func (b *InsertEventBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertEventBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertJudges = `-- name: InsertJudges :batchexec
INSERT INTO judges(id, tournament_id, person_id, first_name, last_name, email)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT(id) DO UPDATE
    SET tournament_id = EXCLUDED.tournament_id,
        person_id     = EXCLUDED.person_id,
        first_name    = EXCLUDED.first_name,
        last_name     = EXCLUDED.last_name,
        email         = EXCLUDED.email
`

type InsertJudgesBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertJudgesParams struct {
	ID           int32
	TournamentID int32
	PersonID     int32
	FirstName    string
	LastName     string
	Email        pgtype.Text
}

func (q *Queries) InsertJudges(ctx context.Context, arg []InsertJudgesParams) *InsertJudgesBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.TournamentID,
			a.PersonID,
			a.FirstName,
			a.LastName,
			a.Email,
		}
		batch.Queue(insertJudges, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertJudgesBatchResults{br, len(arg), false}
}

func (b *InsertJudgesBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertJudgesBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertRooms = `-- name: InsertRooms :batchexec
INSERT INTO rooms(id, site_id, name)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE
    SET site_id = EXCLUDED.site_id,
        name    = EXCLUDED.name
`

type InsertRoomsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertRoomsParams struct {
	ID     int32
	SiteID pgtype.Int4
	Name   pgtype.Text
}

func (q *Queries) InsertRooms(ctx context.Context, arg []InsertRoomsParams) *InsertRoomsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.SiteID,
			a.Name,
		}
		batch.Queue(insertRooms, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertRoomsBatchResults{br, len(arg), false}
}

func (b *InsertRoomsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertRoomsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertRound = `-- name: InsertRound :batchexec
INSERT INTO rounds(id, event_id, number, start_time, published)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT(id) DO UPDATE
    SET event_id   = EXCLUDED.event_id,
        number     = EXCLUDED.number,
        start_time = EXCLUDED.start_time,
        published  = EXCLUDED.published
`

type InsertRoundBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertRoundParams struct {
	ID        int32
	EventID   pgtype.Int4
	Number    int32
	StartTime pgtype.Timestamp
	Published bool
}

func (q *Queries) InsertRound(ctx context.Context, arg []InsertRoundParams) *InsertRoundBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.EventID,
			a.Number,
			a.StartTime,
			a.Published,
		}
		batch.Queue(insertRound, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertRoundBatchResults{br, len(arg), false}
}

func (b *InsertRoundBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertRoundBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertSchool = `-- name: InsertSchool :batchexec
INSERT INTO schools(id, name)
VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE
    SET name = EXCLUDED.name
`

type InsertSchoolBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertSchoolParams struct {
	ID   int32
	Name pgtype.Text
}

func (q *Queries) InsertSchool(ctx context.Context, arg []InsertSchoolParams) *InsertSchoolBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.Name,
		}
		batch.Queue(insertSchool, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertSchoolBatchResults{br, len(arg), false}
}

func (b *InsertSchoolBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertSchoolBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertSections = `-- name: InsertSections :batchexec
INSERT INTO sections(id, round_id, room_id, flight)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE
    SET round_id = EXCLUDED.round_id,
        room_id  = EXCLUDED.room_id,
        flight   = EXCLUDED.flight
`

type InsertSectionsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertSectionsParams struct {
	ID      int32
	RoundID pgtype.Int4
	RoomID  pgtype.Int4
	Flight  int32
}

func (q *Queries) InsertSections(ctx context.Context, arg []InsertSectionsParams) *InsertSectionsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.RoundID,
			a.RoomID,
			a.Flight,
		}
		batch.Queue(insertSections, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertSectionsBatchResults{br, len(arg), false}
}

func (b *InsertSectionsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertSectionsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertSites = `-- name: InsertSites :batchexec
INSERT INTO sites(id, name)
VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE
    SET name = EXCLUDED.name
`

type InsertSitesBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertSitesParams struct {
	ID   int32
	Name pgtype.Text
}

func (q *Queries) InsertSites(ctx context.Context, arg []InsertSitesParams) *InsertSitesBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.Name,
		}
		batch.Queue(insertSites, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertSitesBatchResults{br, len(arg), false}
}

func (b *InsertSitesBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertSitesBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertStudent = `-- name: InsertStudent :batchexec
INSERT INTO students(id, school_id, first_name, middle_name, last_name, grad_year)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT(id) DO UPDATE
    SET school_id   = EXCLUDED.school_id,
        first_name  = EXCLUDED.first_name,
        middle_name = EXCLUDED.middle_name,
        last_name   = EXCLUDED.last_name,
        grad_year   = EXCLUDED.grad_year
`

type InsertStudentBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertStudentParams struct {
	ID         int32
	SchoolID   pgtype.Int4
	FirstName  string
	MiddleName string
	LastName   string
	GradYear   int32
}

func (q *Queries) InsertStudent(ctx context.Context, arg []InsertStudentParams) *InsertStudentBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.SchoolID,
			a.FirstName,
			a.MiddleName,
			a.LastName,
			a.GradYear,
		}
		batch.Queue(insertStudent, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertStudentBatchResults{br, len(arg), false}
}

func (b *InsertStudentBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertStudentBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertStudentEntries = `-- name: InsertStudentEntries :batchexec
INSERT INTO student_entries(student_id, entry_id)
VALUES ($1, $2)
ON CONFLICT(student_id, entry_id) DO NOTHING
`

type InsertStudentEntriesBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertStudentEntriesParams struct {
	StudentID int32
	EntryID   int32
}

func (q *Queries) InsertStudentEntries(ctx context.Context, arg []InsertStudentEntriesParams) *InsertStudentEntriesBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.StudentID,
			a.EntryID,
		}
		batch.Queue(insertStudentEntries, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertStudentEntriesBatchResults{br, len(arg), false}
}

func (b *InsertStudentEntriesBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertStudentEntriesBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
