// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID           int32
	TournamentID pgtype.Int4
	Name         pgtype.Text
}

type School struct {
	ID   int32
	Name pgtype.Text
}

type Tournament struct {
	ID          int32
	Raw         []byte
	Date        pgtype.Text
	Name        pgtype.Text
	UpdatedTime pgtype.Text
}
