// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Tournament struct {
	ID   int32
	Date pgtype.Date
	Name string
	Json []byte
}
