// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteTournament = `-- name: DeleteTournament :exec
DELETE
FROM tournaments
WHERE id = $1
`

func (q *Queries) DeleteTournament(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteTournament, id)
	return err
}

const getLoadedTournaments = `-- name: GetLoadedTournaments :many
SELECT id, updated_time
FROM tournaments
`

type GetLoadedTournamentsRow struct {
	ID          int32
	UpdatedTime pgtype.Text
}

func (q *Queries) GetLoadedTournaments(ctx context.Context) ([]GetLoadedTournamentsRow, error) {
	rows, err := q.db.Query(ctx, getLoadedTournaments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLoadedTournamentsRow
	for rows.Next() {
		var i GetLoadedTournamentsRow
		if err := rows.Scan(&i.ID, &i.UpdatedTime); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadTournament = `-- name: LoadTournament :exec
INSERT INTO tournaments (id, raw)
VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE
    SET raw = EXCLUDED.raw
`

type LoadTournamentParams struct {
	ID  int32
	Raw []byte
}

func (q *Queries) LoadTournament(ctx context.Context, arg LoadTournamentParams) error {
	_, err := q.db.Exec(ctx, loadTournament, arg.ID, arg.Raw)
	return err
}
