// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteTournament = `-- name: DeleteTournament :exec
DELETE
FROM tournaments
WHERE id = $1
`

func (q *Queries) DeleteTournament(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteTournament, id)
	return err
}

const getLatestPublishedRoundsPerEvent = `-- name: GetLatestPublishedRoundsPerEvent :many
SELECT DISTINCT ON (events.name) rounds.event_id   AS event_id,
                                 events.name       AS event_name,
                                 rounds.number     AS round_number,
                                 rounds.id         AS round_id,
                                 rounds.start_time AS start_time
FROM rounds
         JOIN events
              ON events.id = rounds.event_id
WHERE events.tournament_id = $1
  AND published = TRUE
ORDER BY events.name, rounds.number DESC
`

type GetLatestPublishedRoundsPerEventRow struct {
	EventID     pgtype.Int4
	EventName   pgtype.Text
	RoundNumber int32
	RoundID     int32
	StartTime   pgtype.Timestamp
}

func (q *Queries) GetLatestPublishedRoundsPerEvent(ctx context.Context, tournamentID pgtype.Int4) ([]GetLatestPublishedRoundsPerEventRow, error) {
	rows, err := q.db.Query(ctx, getLatestPublishedRoundsPerEvent, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLatestPublishedRoundsPerEventRow
	for rows.Next() {
		var i GetLatestPublishedRoundsPerEventRow
		if err := rows.Scan(
			&i.EventID,
			&i.EventName,
			&i.RoundNumber,
			&i.RoundID,
			&i.StartTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLoadedTournaments = `-- name: GetLoadedTournaments :many
SELECT id, updated_time
FROM tournaments
`

type GetLoadedTournamentsRow struct {
	ID          int32
	UpdatedTime pgtype.Text
}

func (q *Queries) GetLoadedTournaments(ctx context.Context) ([]GetLoadedTournamentsRow, error) {
	rows, err := q.db.Query(ctx, getLoadedTournaments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLoadedTournamentsRow
	for rows.Next() {
		var i GetLoadedTournamentsRow
		if err := rows.Scan(&i.ID, &i.UpdatedTime); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPairingsWithBallots = `-- name: GetPairingsWithBallots :many
WITH unique_section_judges AS (SELECT DISTINCT ON (ballots.section_id, judges.id) ballots.section_id,
                                                                                  judges.id,
                                                                                  judges.first_name,
                                                                                  judges.last_name,
                                                                                  judges.person_id,
                                                                                  ballots.started
                               FROM ballots
                                        LEFT JOIN judges ON ballots.judge_id = judges.id
                                        JOIN sections ON ballots.section_id = sections.id
                               WHERE sections.round_id = ANY ($1::int[])
                                 AND judges.id IS NOT NULL),
     judges_aggregated AS (SELECT section_id,
                                  JSON_AGG(
                                          JSON_BUILD_OBJECT('id', id, 'firstName', first_name, 'lastName', last_name,
                                                            'personId', person_id, 'started', started)
                                  ) AS aggregated_judges
                           FROM unique_section_judges
                           GROUP BY section_id),
     matchups_with_ballots AS (SELECT section_id,
                                      MAX(sections.flight)                                         AS flight,
                                      MAX(rounds.event_id)                                         AS event_id,
                                      MAX(room_id)                                                 AS room_id,
                                      MAX(entry_id) FILTER (WHERE side = 'AFF')                    AS aff_team,
                                      MAX(entry_id) FILTER (WHERE side = 'NEG')                    AS neg_team,
                                      JSON_AGG(
                                      JSON_BUILD_OBJECT('side', side, 'result', result, 'judge', ballots.judge_id)
                                              ) FILTER (WHERE result IS NOT NULL AND side = 'AFF') AS aff_ballots,
                                      JSON_AGG(
                                      JSON_BUILD_OBJECT('side', side, 'result', result, 'judge', ballots.judge_id)
                                              ) FILTER (WHERE result IS NOT NULL AND side = 'NEG') AS neg_ballots
                               FROM ballots
                                        JOIN sections ON ballots.section_id = sections.id
                                        JOIN rounds ON sections.round_id = rounds.id
                               WHERE sections.round_id = ANY ($1::int[])
                               GROUP BY section_id)
SELECT matchups_with_ballots.event_id::int AS event_id,
       matchups_with_ballots.section_id    AS section_id,
       matchups_with_ballots.flight::int   AS flight,
       rooms.id                            AS room_id,
       rooms.name                          AS room_name,
       aff_entries.id                      AS aff_team_entry_id,
       aff_entries.code                    AS aff_team_entry_code,
       neg_entries.id                      AS neg_team_entry_id,
       neg_entries.code                    As neg_team_entry_code,
       matchups_with_ballots.aff_ballots   AS aff_team_ballots,
       matchups_with_ballots.neg_ballots   AS neg_team_ballots,
       judges_aggregated.aggregated_judges AS associated_judges
FROM matchups_with_ballots
         LEFT JOIN entries AS aff_entries ON aff_team = aff_entries.id
         LEFT JOIN entries AS neg_entries ON neg_team = neg_entries.id
         LEFT JOIN rooms ON room_id = rooms.id
         LEFT JOIN judges_aggregated ON matchups_with_ballots.section_id = judges_aggregated.section_id
ORDER BY room_name
`

type GetPairingsWithBallotsRow struct {
	EventID          int32
	SectionID        pgtype.Int4
	Flight           int32
	RoomID           pgtype.Int4
	RoomName         pgtype.Text
	AffTeamEntryID   pgtype.Int4
	AffTeamEntryCode pgtype.Text
	NegTeamEntryID   pgtype.Int4
	NegTeamEntryCode pgtype.Text
	AffTeamBallots   []byte
	NegTeamBallots   []byte
	AssociatedJudges []byte
}

func (q *Queries) GetPairingsWithBallots(ctx context.Context, dollar_1 []int32) ([]GetPairingsWithBallotsRow, error) {
	rows, err := q.db.Query(ctx, getPairingsWithBallots, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPairingsWithBallotsRow
	for rows.Next() {
		var i GetPairingsWithBallotsRow
		if err := rows.Scan(
			&i.EventID,
			&i.SectionID,
			&i.Flight,
			&i.RoomID,
			&i.RoomName,
			&i.AffTeamEntryID,
			&i.AffTeamEntryCode,
			&i.NegTeamEntryID,
			&i.NegTeamEntryCode,
			&i.AffTeamBallots,
			&i.NegTeamBallots,
			&i.AssociatedJudges,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadTournament = `-- name: LoadTournament :exec
INSERT INTO tournaments (id, raw)
VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE
    SET raw = EXCLUDED.raw
`

type LoadTournamentParams struct {
	ID  int32
	Raw []byte
}

func (q *Queries) LoadTournament(ctx context.Context, arg LoadTournamentParams) error {
	_, err := q.db.Exec(ctx, loadTournament, arg.ID, arg.Raw)
	return err
}
