// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package sqlc

import (
	"context"
)

const getLoadedTournaments = `-- name: GetLoadedTournaments :many
SELECT id, name FROM tournaments
`

type GetLoadedTournamentsRow struct {
	ID   int32
	Name string
}

func (q *Queries) GetLoadedTournaments(ctx context.Context) ([]GetLoadedTournamentsRow, error) {
	rows, err := q.db.Query(ctx, getLoadedTournaments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLoadedTournamentsRow
	for rows.Next() {
		var i GetLoadedTournamentsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
